name: Docs Action

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.9.2
        run: mv docs/html docs/docs
      
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
